//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfileSoapRef
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SimilarProfileDto", Namespace="http://schemas.datacontract.org/2004/07/DAL.DTOs")]
    public partial class SimilarProfileDto : object
    {
        
        private System.Nullable<bool> CreatorField;
        
        private string FirstNameField;
        
        private string IsCreatorXmlField;
        
        private string LastNameField;
        
        private ProfileSoapRef.ProfilePictureDto[] ProfilePicturesField;
        
        private string PublicIdentifierField;
        
        private string SubtitleField;
        
        private string SubtitleV2Field;
        
        private string TextActionTargetField;
        
        private string TitleV2Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Creator
        {
            get
            {
                return this.CreatorField;
            }
            set
            {
                this.CreatorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsCreatorXml
        {
            get
            {
                return this.IsCreatorXmlField;
            }
            set
            {
                this.IsCreatorXmlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProfileSoapRef.ProfilePictureDto[] ProfilePictures
        {
            get
            {
                return this.ProfilePicturesField;
            }
            set
            {
                this.ProfilePicturesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PublicIdentifier
        {
            get
            {
                return this.PublicIdentifierField;
            }
            set
            {
                this.PublicIdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subtitle
        {
            get
            {
                return this.SubtitleField;
            }
            set
            {
                this.SubtitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubtitleV2
        {
            get
            {
                return this.SubtitleV2Field;
            }
            set
            {
                this.SubtitleV2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TextActionTarget
        {
            get
            {
                return this.TextActionTargetField;
            }
            set
            {
                this.TextActionTargetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TitleV2
        {
            get
            {
                return this.TitleV2Field;
            }
            set
            {
                this.TitleV2Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfilePictureDto", Namespace="http://schemas.datacontract.org/2004/07/DAL.DTOs")]
    public partial class ProfilePictureDto : object
    {
        
        private System.Nullable<int> HeightField;
        
        private string UrlField;
        
        private System.Nullable<int> WidthField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Height
        {
            get
            {
                return this.HeightField;
            }
            set
            {
                this.HeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                this.UrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Width
        {
            get
            {
                return this.WidthField;
            }
            set
            {
                this.WidthField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProfileSoapRef.IProfileSearchService")]
    public interface IProfileSearchService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfileSearchService/SearchByKeyword", ReplyAction="http://tempuri.org/IProfileSearchService/SearchByKeywordResponse")]
        System.Threading.Tasks.Task<ProfileSoapRef.SimilarProfileDto[]> SearchByKeywordAsync(string keyword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IProfileSearchServiceChannel : ProfileSoapRef.IProfileSearchService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ProfileSearchServiceClient : System.ServiceModel.ClientBase<ProfileSoapRef.IProfileSearchService>, ProfileSoapRef.IProfileSearchService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ProfileSearchServiceClient() : 
                base(ProfileSearchServiceClient.GetDefaultBinding(), ProfileSearchServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IProfileSearchService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProfileSearchServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ProfileSearchServiceClient.GetBindingForEndpoint(endpointConfiguration), ProfileSearchServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProfileSearchServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ProfileSearchServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProfileSearchServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ProfileSearchServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProfileSearchServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ProfileSoapRef.SimilarProfileDto[]> SearchByKeywordAsync(string keyword)
        {
            return base.Channel.SearchByKeywordAsync(keyword);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IProfileSearchService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IProfileSearchService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:5150/soap/ProfileService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ProfileSearchServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IProfileSearchService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ProfileSearchServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IProfileSearchService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IProfileSearchService,
        }
    }
}
