USE [master]
GO
/****** Object:  Database [IISProjectDB]    Script Date: 16.6.2025. 23:56:52 ******/
CREATE DATABASE [IISProjectDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'IISProjectDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\IISProjectDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'IISProjectDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\IISProjectDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [IISProjectDB] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [IISProjectDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [IISProjectDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [IISProjectDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [IISProjectDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [IISProjectDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [IISProjectDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [IISProjectDB] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [IISProjectDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [IISProjectDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [IISProjectDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [IISProjectDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [IISProjectDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [IISProjectDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [IISProjectDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [IISProjectDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [IISProjectDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [IISProjectDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [IISProjectDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [IISProjectDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [IISProjectDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [IISProjectDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [IISProjectDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [IISProjectDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [IISProjectDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [IISProjectDB] SET  MULTI_USER 
GO
ALTER DATABASE [IISProjectDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [IISProjectDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [IISProjectDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [IISProjectDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [IISProjectDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [IISProjectDB] SET QUERY_STORE = OFF
GO
USE [IISProjectDB]
GO
/****** Object:  Table [dbo].[AppUser]    Script Date: 16.6.2025. 23:56:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AppUser](
	[IDUser] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](100) NOT NULL,
	[RefreshToken] [nvarchar](500) NULL,
	[RefreshTokenExpiry] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IDUser] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProfilePictures]    Script Date: 16.6.2025. 23:56:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProfilePictures](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ProfileId] [int] NOT NULL,
	[Width] [int] NOT NULL,
	[Height] [int] NOT NULL,
	[Url] [nvarchar](500) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Profiles]    Script Date: 16.6.2025. 23:56:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Profiles](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[PublicIdentifier] [nvarchar](200) NOT NULL,
	[FirstName] [nvarchar](100) NOT NULL,
	[LastName] [nvarchar](100) NOT NULL,
	[TitleV2] [nvarchar](255) NOT NULL,
	[TextActionTarget] [nvarchar](500) NOT NULL,
	[Subtitle] [nvarchar](500) NULL,
	[SubtitleV2] [nvarchar](500) NULL,
	[IsCreator] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[PublicIdentifier] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ProfilePictures]  WITH CHECK ADD  CONSTRAINT [FK_ProfilePictures_Profiles] FOREIGN KEY([ProfileId])
REFERENCES [dbo].[Profiles] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ProfilePictures] CHECK CONSTRAINT [FK_ProfilePictures_Profiles]
GO
USE [master]
GO
ALTER DATABASE [IISProjectDB] SET  READ_WRITE 
GO
